name: Auto Merge PR
on:
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
    
jobs:
  auto-merge:
    name: Auto-Merge Admin PR
    runs-on: macos-latest
    steps:
      - name: Check permissions
        id: check-permissions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          response=$(gh api repos/${{ github.repository }}/collaborators/${{ github.actor }}/permission)
          role=$(echo "$response" | jq -r '.role_name')
          if [[ "$role" == "admin" ]]; then
            echo "authorized=true" >> "$GITHUB_OUTPUT"
          else
            echo "authorized=false" >> "$GITHUB_OUTPUT"
          fi
   
      - name: Create github app token
        id: app-token
        if: steps.check-permissions.outputs.authorized == 'true'
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Approve and squash the pull request
        if: steps.check-permissions.outputs.authorized == 'true'
        env: 
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          PR_URL: ${{github.event.pull_request.html_url}}
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --admin -s "$PR_URL"
