name: Clear Deployments

on:
  workflow_dispatch:

jobs:
  delete-deployments:
    name: Delete 
    runs-on: macos-latest
    permissions: write-all
    steps:
      - env:
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: |
          for ID in $(gh api --method GET "repos/$REPO/deployments?per_page=100" | jq -r ".[] | .id" | tr -d "\r")
          do
            gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \ 
            --method POST /repos/$REPO/deployments/$ID/statuses -f "state=inactive"

            gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --method DELETE repos/$REPO/deployments/$ID
          done
