name: Deploy iOS App

on:
  workflow_dispatch:

jobs:
  deploy_to_testflight:
    name: Deploy To TestFlight
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up ruby environment
        uses: ruby/setup-ruby@v1
        with:
          working-directory: ios
          bundler-cache: true

      - name: Load passphrase from secrets
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          cd ios/fastlane
          mkdir Private
          echo "$PASSPHRASE" > Private/passphrase
         
      - name: Archive and Upload
        run: |
          sudo xcode-select -s /Applications/Xcode_16.1.app
          sudo xcode-select -p
          cd ios
          bundle exec pod install
          bundle exec fastlane deploy_to_testflight

  deploy_to_firebase:
    name: Deploy To Firebase
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up ruby environment
        uses: ruby/setup-ruby@v1
        with:
          working-directory: ios
          bundler-cache: true

      - name: Load passphrase from secrets
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          cd ios/fastlane
          mkdir Private
          echo "$PASSPHRASE" > Private/passphrase
         
      - name: Archive and Upload
        run: |
          sudo xcode-select -s /Applications/Xcode_16.1.app
          sudo xcode-select -p
          cd ios
          bundle exec pod install
          bundle exec fastlane deploy_to_firebase
