name: Deploy Flutter iOS (Firebase)

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Upload To TestFlight
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up ruby environment
        uses: ruby/setup-ruby@v1
        with:
          working-directory: flutter/ios
          bundler-cache: true
      
      - name: Set up fvm environment
        run: |
          brew tap leoafarias/fvm
          brew install fvm
          cd flutter
          fvm install
          fvm flutter pub get
          fvm flutter precache --ios

      - name: Load passphrase from secrets
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          cd flutter/ios/fastlane
          mkdir Private
          echo "$PASSPHRASE" > Private/passphrase
         
      - name: Archive and Upload
        run: |
          cd flutter/ios
          bundle exec pod install
          bundle exec fastlane beta_firebase
