name: List Admin

on:
  workflow_dispatch:

jobs:
  check-admin:
    runs-on: ubuntu-latest
    steps:
      - name: Get Actor Permissions
        id: check-auto-merge-permissions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/${{ github.repository }}/collaborators/${{ github.actor }}/permission > response.json
          cat response.json
          gh api repos/${{ github.repository }}/collaborators/${{ github.actor }}/permission --jq '.permission' > permission.txt
          cat permission.txt
          echo "PERMISSION=$(cat permission.txt)" >> $GITHUB_ENV
          echo "authorized=true" >> "$GITHUB_OUTPUT"

      - name: Check If Admin
        if: steps.check-permissions.outputs.authorized != 'true'
        run: |
          echo "Can Merge"
        
