name: List Admin

on:
  workflow_dispatch:

jobs:
  check-admin:
    runs-on: ubuntu-latest
    steps:
      - name: Get Actor Permissions
        id: get-permissions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/${{ github.repository }}/collaborators/${{ github.actor }}/permission > response.json
          cat response.json
          gh api repos/${{ github.repository }}/collaborators/${{ github.actor }}/permission --jq '.permission' > permission.txt
          cat permission.txt
          echo "PERMISSION=$(cat permission.txt)" >> $GITHUB_ENV

      - name: Check If Admin
        run: |
          if [ "$PERMISSION" == "admin" ]; then
            echo "Actor ${{ github.actor }} is an admin."
          else
            echo "Actor ${{ github.actor }} is not an admin."
            exit 1
          fi
