name: List Xcode Versions

on:
  workflow_dispatch:

jobs:
  list-xcode:
    runs-on: macos-latest
    steps:
      - name: List Xcode Versions
        run: |
          echo "Available Xcode versions:"
          ls /Applications | grep Xcode
      - name: Show Default Xcode Version
        run: xcodebuild -version
      - name: Show Xcode-select Path
        run: xcode-select -p